const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(__dirname+'/迈克尔孙波长计算器.html','utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const elements=new Map();
const document={getElementById(id){if(!elements.has(id))elements.set(id,{value:'',textContent:'',innerHTML:'',disabled:false,addEventListener(){},focus(){}});return elements.get(id)},querySelector(){return {innerText:'公式与适用条件'}}};
const context=vm.createContext({document,console});vm.runInContext(script,context);
const calc=(...args)=>context.compute(...args),near=(a,b,tol=1e-8)=>assert(Math.abs(a-b)<tol,`${a} != ${b}`);
const k=[0,50,100,150,200,250,300,350,400,450];
const d=k.map(x=>14+x*.0003164);
let r=calc(k,d,.0001,632.8);near(r.lambda,632.8);near(r.ua,0);near(r.ub,.0001/Math.sqrt(3));near(r.ul,2/50*1e6*.0001/Math.sqrt(3));
near(calc(k,d.map(x=>-x),.0001).lambda,632.8);
r=calc([0,50,100,150],[0,.01,.03,.05],0);near(r.mean,.0175);near(r.ua,.0025);near(r.lambda,700);near(r.ul,100);
assert.equal(calc(k,d).uc,null);
assert.throws(()=>calc([0,50,100],[1,2,3]));assert.throws(()=>calc([0,50,100,151],[1,2,3,4]));assert.throws(()=>calc([0,50,100,150],[1,2,1,4]));assert.throws(()=>calc(k,d,-1));assert.throws(()=>calc(k,d.slice(1)));assert.throws(()=>context.parseNumbers('1, abc','d'));
assert.deepEqual(Array.from(context.parseNumbers('0，50\n100\t150；200','k')),[0,50,100,150,200]);
assert.equal(context.roundedReport(632.884,2.3094),'632.9 ± 2.3 nm');
document.getElementById('example').onclick();assert.match(document.getElementById('wavelength').textContent,/632/);assert.equal(document.getElementById('export').disabled,false);assert.match(document.getElementById('rows').innerHTML,/1 ↔ 6/);
document.getElementById('k').value='0,50';document.getElementById('calculate').onclick();assert.equal(document.getElementById('export').disabled,true);assert.equal(document.getElementById('wavelength').textContent,'—');
document.getElementById('clear').onclick();assert.equal(document.getElementById('d').value,'');
console.log('PASS: exact wavelength, Type A/B propagation, normalization, reverse motion, missing B, invalid input, parsing, rounding and UI actions.');
